name: Deploy

on:
  push:
    branches:
      - main   # or whichever branch you want to auto-deploy

jobs:
  deploy:
    runs-on: self-hosted   # your EC2 runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'

      - name: Enable Corepack
        run: |
          corepack enable
          # Option A → Yarn 4 (if you migrated lockfile)
          corepack prepare yarn@4.9.4 --activate
          # Option B → Yarn 1 (if you kept old lockfile)
          # corepack prepare yarn@1.22.22 --activate

      - name: Install dependencies
        run: |
          # Option A
          yarn install --immutable --immutable-cache
          # Option B
          # yarn install --frozen-lockfile

      - name: Build project
        run: yarn build

      - name: Deploy
        run: |
          pm2 restart ecosystem.config.js || pm2 start ecosystem.config.js
          # OR whatever command you use to run Node/Express
